### ISSUE TITLE
Add packages to base box

### ISSUE THREAD

**Issue by rnathanday** [datadryad/vagrant-dryad#26]
Selenium tests can be run in a vagrant-dryad VM using a headless Firefox instance, once these dependencies have been installed, which I did on my own instance using an `apt-get` call:
- xvfb
- firefox

Modulo whether having Selenium tests running in a vagrant-dryad VM is a priority, it might be useful to add them to the stock VM or to the Vagrantfile. I am not sure which would be preferable, especially given how quickly Firefox releases occur (not sure about xvfb).

**Comment by ryscher** [comment]
This issue is no longer relevant.
