### ISSUE TITLE
dspace.baseUrl needs to be set in settings.xml.j2

### ISSUE THREAD

**Issue by jar398** [datadryad/vagrant-dryad#29]
It needs to include the port; otherwise SWORD deposit doesn't work.  Something like

```
    <default.dspace.baseUrl>http://{{ dryad.hostname }}:{{ dryad.port }}</default.dspace.baseUrl>
```

although I haven't tested this.

I don't understand how this stuff is processed but I wonder if, given the above, the setting of default.db.url can be removed from settings.xml.j2, given that in dpsace.cfg it's set from dspace.baseUrl.

**Comment by ryscher** [comment]
This issue is no longer relevant.
