### ISSUE TITLE
Install db before deploy, not the other way around

### ISSUE THREAD

**Issue by jar398** [datadryad/vagrant-dryad#32]
In https://github.com/datadryad/vagrant-dryad/#developing-building-testing-deploying
1. Deploy dryad         /home/vagrant/bin/deploy_dryad.sh
2. Install database     /home/vagrant/bin/install_dryad_database.sh

should be the other way around:
1. Install database     /home/vagrant/bin/install_dryad_database.sh
2. Deploy dryad         /home/vagrant/bin/deploy_dryad.sh

If you do it in the order given, you get about ten errors similar to:

```
 [java] org.postgresql.util.PSQLException: ERROR: relation "metadatafieldregistry" does not exist
```

and the build (deploy) fails.

I haven't tested a fresh setup with just install / deploy; I did deploy (fail) / install / deploy and it seems fine. So I don't know for sure that the first failed build isn't necessary for proper functioning. But I would expect it to be unnecessary.

**Comment by ryscher** [comment]
Has been fixed long ago.
