### ISSUE TITLE
Missing 'bag' executable

### ISSUE THREAD

**Issue by jar398** [datadryad/vagrant-dryad#35]
dspace.cfg has:
    bagit.executable = ${default.bagit.executable}
settings.xml has:
    <default.bagit.executable>/home/dryad/bagit-3.6/bin/bag</default.bagit.executable>
but:
    ls -l /home/dryad/bagit-3.6/bin/bag
    ls: cannot access /home/dryad/bagit-3.6/bin/bag: No such file or directory

There are releases here (but not 3.6), and I think we can assume backward compatibility.
https://github.com/LibraryOfCongress/bagit-java/releases

**Comment by ryscher** [comment]
This issue is no longer relevant.
