### ISSUE TITLE
Test version of dspace.cfg is missing settings required by tests

### ISSUE THREAD

**Issue by jar398** [datadryad/vagrant-dryad#37]
test/config/dspace.cfg is a special file with minimal settings. When running tests it would better if it were simply a modified version of the 'real' dspace.cfg, since a test might require arbitrary settings from dspace.cfg.

Also test/config/dspace.cfg should pick up changes that a developer makes to dspace/config/dspace.cfg right away, since those changes will be important for development and testing.

May I suggest that in install_dryad_test_database.sh, the sed commands at the bottom should take their input from dryad_repo/dspace/config/dspace.cfg, instead of /opt/dryad/test/config/dspace.cfg, and write them to /opt/dryad/test/config/dspace.cfg.

If I get confirmation that this is the right approach I'll go ahead and prepare a PR to do this.

**Comment by mdiggory** [comment]
Jon,

This is actually what we do in alter version of dspace, when the testEnviornment.zip is generated for the JUnit tests during build. This may give you some ideas on how its done:

https://github.com/DSpace/DSpace/blob/master/pom.xml#L324

I agree that filtering the dspace.cfg and/or other config in dryad_repo/dspace/config in the manner that the mvn/ant build does would be a good idea. I just had to add to adjust the test environment to correct for a travis failures:

https://github.com/datadryad/dryad-repo/pull/901/files#diff-253c89cc4fb0a3ebee366ec17af752b7R51

**Comment by jar398** [comment]
See #38
